name: Pylint

on:
  push:
    paths: ['**/*.py']
  pull_request:
    paths: ['**/*.py']

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint networkx tqdm
    - name: Lint with pylint
      run: |
        pylint lace/__init__.py lace/build_supertranscript.py lace/lace_run.py setup.py --fail-under=10.0
